name: CI

on: push

jobs:

  test:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up virtualenv, install from source
        run: make config
      - name: Run unit tests and static analysis
        run: make test
      - name: Build distributable package
        run: make build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: py${{ matrix.python-version }}-mpyk.tar.gz
          path: dist/*.tar.gz
          retention-days: 1

  install_pkg:
    name: Install on Python ${{ matrix.python-version }}
    needs: test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install publishing tool
        run: pip install --upgrade pip setuptools wheel twine
      - name: Download cached sdist package
        uses: actions/download-artifact@v2
        with:
          name: py${{ matrix.python-version }}-mpyk.tar.gz
      - name: List files
        run: find . -type f | sort
      - name: Install the package globally
        run: for pkg in $(find *.tar.gz); do pip install $pkg; done

  publish:
    name: Publish the package
    needs:
      - test
      - install_pkg
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install publishing tool
        run: pip install --upgrade pip setuptools wheel twine
      - name: Download cached sdist package
        uses: actions/download-artifact@v2
        with:
          name: py3.9-mpyk.tar.gz
      - name: Publish the package
        run: twine upload -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }} mpyk-*.tar.gz
